server:
  servlet:
    context-path: /
  port: 8080
  tomcat:
    uri-encoding: utf-8
  error:
    whitelabel:
      enabled: false


spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
    servlet:
      load-on-startup: 1
  thymeleaf:
    cache: false
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/mp3_2?useUnicode\=true&characterEncoding\=UTF-8
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
      com:
    shangmao:
      demo:
        dao: trace
